services:
    _defaults:
        autowire: true
        public: false

    Villermen\Minecraft\Controller\:
        resource: '../src/Controller/*'
        public: true

    Villermen\Minecraft\Migration\:
        resource: '../src/Migration/*'
        public: true

    Villermen\Minecraft\Service\:
        resource: '../src/Service/*'
